from typing import Any, List, Optional, Tuple, final

from geomcore.curves import BSplineCurve3D

from . import curves, surfaces

@final
class Point3D:
    def __new__(cls, x: float, y: float, z: float) -> Point3D: ...
    @staticmethod
    def origin() -> Point3D: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
    def distance(self, other: Point3D) -> float: ...
    def __repr__(self) -> str: ...

@final
class Point2D:
    def __new__(cls, x: float, y: float) -> Point2D: ...
    @staticmethod
    def origin() -> Point2D: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    def distance(self, other: Point2D) -> float: ...

@final
class Vector3D:
    def __new__(cls, x: float, y: float, z: float) -> Vector3D: ...
    @staticmethod
    def zero() -> Vector3D: ...
    @staticmethod
    def x() -> Vector3D: ...
    @staticmethod
    def y() -> Vector3D: ...
    @staticmethod
    def z() -> Vector3D: ...
    def components(self) -> Tuple[float, float, float]: ...
    def dot(self, other: Vector3D) -> float: ...
    def cross(self, other: Vector3D) -> Vector3D: ...
    def magnitude(self) -> float: ...

@final
class Vector2D:
    def __new__(cls, x: float, y: float) -> Vector2D: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    def dot(self, other: Vector2D) -> float: ...
    def magnitude(self) -> float: ...

@final
class Axis3D:
    def __new__(cls, origin: Point3D, direction: Vector3D) -> Axis3D: ...
    def origin(self) -> Point3D: ...
    def direction(self) -> Vector3D: ...

@final
class Frame3D:
    def __new__(cls, origin: Point3D, z_direction: Vector3D, x_hint: Vector3D) -> Frame3D: ...
    @staticmethod
    def from_z(origin: Point3D, z_direction: Vector3D) -> Frame3D: ...
    @staticmethod
    def world() -> Frame3D: ...
    def origin(self) -> Point3D: ...
    def x_direction(self) -> Vector3D: ...
    def y_direction(self) -> Vector3D: ...
    def z_direction(self) -> Vector3D: ...

@final
class Tolerance:
    def __new__(
        cls, confusion: float = ..., angular: float = ..., parametric: float = ...
    ) -> Tolerance: ...
    @staticmethod
    def default() -> Tolerance: ...
    @property
    def confusion(self) -> float: ...
    @property
    def angular(self) -> float: ...
    @property
    def parametric(self) -> float: ...
    def __repr__(self) -> str: ...

@final
class Transform:
    @staticmethod
    def identity() -> Transform: ...
    @staticmethod
    def translation(offset: Vector3D) -> Transform: ...
    @staticmethod
    def rotation(axis: Axis3D, angle: float) -> Transform: ...
    @staticmethod
    def scaling(center: Point3D, factor: float) -> Transform: ...
    @staticmethod
    def mirror_point(center: Point3D) -> Transform: ...
    @staticmethod
    def mirror_axis(axis: Axis3D) -> Transform: ...
    @staticmethod
    def mirror_plane(frame: Frame3D) -> Transform: ...
    def then(self, next: Transform) -> Transform: ...
    def apply_point(self, p: Point3D) -> Point3D: ...
    def apply_vector(self, v: Vector3D) -> Vector3D: ...

def intersect_curve_surface(
    curve: Any, surface: Any, tol: Optional[Tolerance] = ...
) -> List[Tuple[float, Tuple[float, float], Point3D]]: ...
def intersect_marching(
    surface_a: Any, surface_b: Any, tol: Optional[Tolerance] = ...
) -> List[BSplineCurve3D]: ...
def parametrize_numeric(
    curve: Any, surface: Any, n: int = ..., tol: Optional[Tolerance] = ...
) -> List[Tuple[float, float]]: ...
def curve_curve_extrema(
    curve_a: Any, curve_b: Any, tol: Optional[Tolerance] = ...
) -> List[Tuple[float, float, float]]: ...
def intersect_curve_curve(
    curve_a: Any, curve_b: Any, tol: Optional[Tolerance] = ...
) -> List[Tuple[float, Point3D, float]]: ...

__all__ = [
    "Axis3D",
    "Frame3D",
    "Point2D",
    "Point3D",
    "Tolerance",
    "Transform",
    "Vector2D",
    "Vector3D",
    "curve_curve_extrema",
    "curves",
    "intersect_curve_curve",
    "intersect_curve_surface",
    "intersect_marching",
    "parametrize_numeric",
    "surfaces",
]
