from typing import Any, List, Optional, Tuple, final

from geomcore import Axis3D, Frame3D, Point2D, Point3D, Tolerance, Vector2D, Vector3D

@final
class Line3D:
    def __new__(cls, origin: Point3D, direction: Vector3D) -> Line3D: ...
    @staticmethod
    def from_axis(axis: Axis3D) -> Line3D: ...
    @staticmethod
    def from_two_points(p1: Point3D, p2: Point3D) -> Line3D: ...
    def origin(self) -> Point3D: ...
    def direction(self) -> Vector3D: ...
    def eval_point(self, u: float) -> Point3D: ...
    def eval_points(self, us: List[float]) -> List[Point3D]: ...
    def eval_derivative(self, u: float, order: int) -> Vector3D: ...
    def parameter_of(self, point: Point3D) -> float: ...
    def contains(self, point: Point3D, tol: Optional[Tolerance] = ...) -> bool: ...
    def project_point(
        self, point: Point3D, tol: Optional[Tolerance] = ...
    ) -> Tuple[float, float]: ...
    def project_points(
        self, points: List[Point3D], tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float]]: ...
    def intersect_plane(self, plane: Any, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_sphere(self, sphere: Any, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_cylinder(
        self, cylinder: Any, tol: Optional[Tolerance] = ...
    ) -> Tuple[str, Any]: ...
    def intersect_cone(self, cone: Any, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_line(self, other: Line3D, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_circle(
        self, circle: Circle3D, tol: Optional[Tolerance] = ...
    ) -> Tuple[str, Any]: ...
    def parametrize_on(self, surface: Any) -> Any: ...

@final
class Circle3D:
    def __new__(cls, center: Point3D, normal: Vector3D, radius: float) -> Circle3D: ...
    @staticmethod
    def from_axis(axis: Axis3D, radius: float) -> Circle3D: ...
    @staticmethod
    def from_frame(frame: Frame3D, radius: float) -> Circle3D: ...
    @staticmethod
    def from_three_points(p1: Point3D, p2: Point3D, p3: Point3D) -> Circle3D: ...
    def center(self) -> Point3D: ...
    def radius(self) -> float: ...
    def circumference(self) -> float: ...
    def disk_area(self) -> float: ...
    def normal(self) -> Vector3D: ...
    def eval_point(self, u: float) -> Point3D: ...
    def eval_points(self, us: List[float]) -> List[Point3D]: ...
    def eval_derivative(self, u: float, order: int) -> Vector3D: ...
    def parameter_of(self, point: Point3D) -> float: ...
    def contains(self, point: Point3D, tol: Optional[Tolerance] = ...) -> bool: ...
    def project_point(
        self, point: Point3D, tol: Optional[Tolerance] = ...
    ) -> Tuple[float, float]: ...
    def project_points(
        self, points: List[Point3D], tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float]]: ...
    def parametrize_on(self, surface: Any) -> Any: ...
    def intersect_circle(
        self, other: Circle3D, tol: Optional[Tolerance] = ...
    ) -> Tuple[str, Any]: ...
    def intersect_plane(self, plane: Any, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_sphere(self, sphere: Any, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_cylinder(
        self, cylinder: Any, tol: Optional[Tolerance] = ...
    ) -> Tuple[str, Any]: ...
    def intersect_cone(self, cone: Any, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...

@final
class Ellipse3D:
    def __new__(
        cls,
        center: Point3D,
        normal: Vector3D,
        x_direction: Vector3D,
        major_radius: float,
        minor_radius: float,
    ) -> Ellipse3D: ...
    @staticmethod
    def from_frame(frame: Frame3D, major_radius: float, minor_radius: float) -> Ellipse3D: ...
    @staticmethod
    def from_center_and_points(center: Point3D, s1: Point3D, s2: Point3D) -> Ellipse3D: ...
    def center(self) -> Point3D: ...
    def major_radius(self) -> float: ...
    def minor_radius(self) -> float: ...
    def area(self) -> float: ...
    def eval_point(self, u: float) -> Point3D: ...
    def eval_points(self, us: List[float]) -> List[Point3D]: ...
    def eval_derivative(self, u: float, order: int) -> Vector3D: ...
    def parameter_of(self, point: Point3D) -> float: ...
    def contains(self, point: Point3D, tol: Optional[Tolerance] = ...) -> bool: ...
    def extrema(
        self, point: Point3D, tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float]]: ...
    def project_point(
        self, point: Point3D, tol: Optional[Tolerance] = ...
    ) -> Tuple[float, float]: ...
    def project_points(
        self, points: List[Point3D], tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float]]: ...
    def intersect_plane(self, plane: Any, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_sphere(self, sphere: Any, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_cylinder(
        self, cylinder: Any, tol: Optional[Tolerance] = ...
    ) -> Tuple[str, Any]: ...
    def intersect_cone(self, cone: Any, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def parametrize_on(self, surface: Any) -> Any: ...

@final
class Parabola3D:
    def __new__(
        cls, apex: Point3D, normal: Vector3D, x_direction: Vector3D, focal: float
    ) -> Parabola3D: ...
    @staticmethod
    def from_frame(frame: Frame3D, focal: float) -> Parabola3D: ...
    def focal(self) -> float: ...
    def eval_point(self, u: float) -> Point3D: ...
    def eval_points(self, us: List[float]) -> List[Point3D]: ...
    def eval_derivative(self, u: float, order: int) -> Vector3D: ...
    def parameter_of(self, point: Point3D) -> float: ...
    def contains(self, point: Point3D, tol: Optional[Tolerance] = ...) -> bool: ...
    def extrema(
        self, point: Point3D, tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float]]: ...
    def project_point(
        self, point: Point3D, tol: Optional[Tolerance] = ...
    ) -> Tuple[float, float]: ...
    def project_points(
        self, points: List[Point3D], tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float]]: ...
    def intersect_plane(self, plane: Any, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_sphere(self, sphere: Any, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_cylinder(
        self, cylinder: Any, tol: Optional[Tolerance] = ...
    ) -> Tuple[str, Any]: ...
    def intersect_cone(self, cone: Any, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def parametrize_on(self, surface: Any) -> Any: ...

@final
class Hyperbola3D:
    def __new__(
        cls,
        center: Point3D,
        normal: Vector3D,
        x_direction: Vector3D,
        major_radius: float,
        minor_radius: float,
    ) -> Hyperbola3D: ...
    @staticmethod
    def from_frame(frame: Frame3D, major_radius: float, minor_radius: float) -> Hyperbola3D: ...
    @staticmethod
    def from_center_and_points(center: Point3D, s1: Point3D, s2: Point3D) -> Hyperbola3D: ...
    def center(self) -> Point3D: ...
    def major_radius(self) -> float: ...
    def minor_radius(self) -> float: ...
    def eval_point(self, u: float) -> Point3D: ...
    def eval_points(self, us: List[float]) -> List[Point3D]: ...
    def eval_derivative(self, u: float, order: int) -> Vector3D: ...
    def parameter_of(self, point: Point3D) -> float: ...
    def contains(self, point: Point3D, tol: Optional[Tolerance] = ...) -> bool: ...
    def extrema(
        self, point: Point3D, tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float]]: ...
    def project_point(
        self, point: Point3D, tol: Optional[Tolerance] = ...
    ) -> Tuple[float, float]: ...
    def project_points(
        self, points: List[Point3D], tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float]]: ...
    def intersect_plane(self, plane: Any, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_sphere(self, sphere: Any, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_cylinder(
        self, cylinder: Any, tol: Optional[Tolerance] = ...
    ) -> Tuple[str, Any]: ...
    def intersect_cone(self, cone: Any, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def parametrize_on(self, surface: Any) -> Any: ...

@final
class BSplineCurve3D:
    def __new__(
        cls,
        degree: int,
        poles: List[Point3D],
        knots: List[float],
        multiplicities: List[int],
        periodic: bool,
    ) -> BSplineCurve3D: ...
    @staticmethod
    def new_rational(
        degree: int,
        poles: List[Point3D],
        weights: List[float],
        knots: List[float],
        multiplicities: List[int],
        periodic: bool,
    ) -> BSplineCurve3D: ...
    @staticmethod
    def interpolate(
        points: List[Point3D], degree: int, parametrization: str = ...
    ) -> BSplineCurve3D: ...
    @staticmethod
    def approximate(
        points: List[Point3D], degree: int, num_poles: int, parametrization: str = ...
    ) -> BSplineCurve3D: ...
    def degree(self) -> int: ...
    def is_periodic(self) -> bool: ...
    def is_rational(self) -> bool: ...
    def bounds(self) -> Tuple[float, float]: ...
    def contains(self, point: Point3D, tol: Optional[Tolerance] = ...) -> bool: ...
    def extrema(
        self, point: Point3D, tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float]]: ...
    def project_point(
        self, point: Point3D, tol: Optional[Tolerance] = ...
    ) -> Tuple[float, float]: ...
    def project_points(
        self, points: List[Point3D], tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float]]: ...
    def eval_point(self, u: float) -> Point3D: ...
    def eval_points(self, us: List[float]) -> List[Point3D]: ...
    def eval_derivative(self, u: float, order: int) -> Vector3D: ...
    def parametrize_on(self, surface: Any) -> Any: ...

@final
class Line2D:
    def __new__(cls, origin: Point2D, direction: Vector2D) -> Line2D: ...
    def origin(self) -> Point2D: ...
    def direction(self) -> Vector2D: ...
    def eval_point(self, u: float) -> Point2D: ...
    def eval_points(self, us: List[float]) -> List[Point2D]: ...
    def eval_derivative(self, u: float, order: int) -> Vector2D: ...
    def parameter_of(self, point: Point2D) -> float: ...
    def contains(self, point: Point2D, tol: Optional[Tolerance] = ...) -> bool: ...
    def project_point(
        self, point: Point2D, tol: Optional[Tolerance] = ...
    ) -> Tuple[float, float]: ...
    def project_points(
        self, points: List[Point2D], tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float]]: ...
    def intersect_line(self, other: Line2D, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_circle(
        self, circle: Circle2D, tol: Optional[Tolerance] = ...
    ) -> Tuple[str, Any]: ...
    def __repr__(self) -> str: ...

@final
class Circle2D:
    def __new__(cls, center: Point2D, radius: float) -> Circle2D: ...
    def center(self) -> Point2D: ...
    def radius(self) -> float: ...
    def eval_point(self, u: float) -> Point2D: ...
    def eval_points(self, us: List[float]) -> List[Point2D]: ...
    def eval_derivative(self, u: float, order: int) -> Vector2D: ...
    def parameter_of(self, point: Point2D) -> float: ...
    def contains(self, point: Point2D, tol: Optional[Tolerance] = ...) -> bool: ...
    def project_point(
        self, point: Point2D, tol: Optional[Tolerance] = ...
    ) -> Tuple[float, float]: ...
    def project_points(
        self, points: List[Point2D], tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float]]: ...
    def intersect_circle(
        self, other: Circle2D, tol: Optional[Tolerance] = ...
    ) -> Tuple[str, Any]: ...
    def __repr__(self) -> str: ...

__all__ = [
    "BSplineCurve3D",
    "Circle2D",
    "Circle3D",
    "Ellipse3D",
    "Hyperbola3D",
    "Line2D",
    "Line3D",
    "Parabola3D",
]
