from typing import Any, List, Optional, Tuple, final

from geomcore import Axis3D, Frame3D, Point3D, Tolerance, Vector3D
from geomcore.curves import Circle3D

@final
class Plane:
    def __new__(cls, point: Point3D, normal: Vector3D) -> Plane: ...
    @staticmethod
    def from_frame(frame: Frame3D) -> Plane: ...
    @staticmethod
    def from_three_points(p1: Point3D, p2: Point3D, p3: Point3D) -> Plane: ...
    @staticmethod
    def from_coefficients(a: float, b: float, c: float, d: float) -> Plane: ...
    def normal(self) -> Vector3D: ...
    def eval_point(self, u: float, v: float) -> Point3D: ...
    def eval_points(self, uvs: List[Tuple[float, float]]) -> List[Point3D]: ...
    def eval_derivative(self, u: float, v: float, du: int, dv: int) -> Vector3D: ...
    def parameters_of(self, point: Point3D) -> Tuple[float, float]: ...
    def contains(self, point: Point3D, tol: Optional[Tolerance] = ...) -> bool: ...
    def project_point(
        self, point: Point3D, tol: Optional[Tolerance] = ...
    ) -> Tuple[float, float, float]: ...
    def project_points(
        self, points: List[Point3D], tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float, float]]: ...
    def intersect_plane(self, other: Plane, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_sphere(self, sphere: Sphere, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_cylinder(
        self, cylinder: Cylinder, tol: Optional[Tolerance] = ...
    ) -> Tuple[str, Any]: ...
    def intersect_cone(self, cone: Cone, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...

@final
class Cylinder:
    def __new__(cls, center: Point3D, axis_direction: Vector3D, radius: float) -> Cylinder: ...
    @staticmethod
    def from_frame(frame: Frame3D, radius: float) -> Cylinder: ...
    @staticmethod
    def from_axis(axis: Axis3D, radius: float) -> Cylinder: ...
    @staticmethod
    def from_circle(circle: Circle3D) -> Cylinder: ...
    def radius(self) -> float: ...
    def eval_point(self, u: float, v: float) -> Point3D: ...
    def eval_points(self, uvs: List[Tuple[float, float]]) -> List[Point3D]: ...
    def eval_derivative(self, u: float, v: float, du: int, dv: int) -> Vector3D: ...
    def parameters_of(self, point: Point3D) -> Tuple[float, float]: ...
    def contains(self, point: Point3D, tol: Optional[Tolerance] = ...) -> bool: ...
    def project_point(
        self, point: Point3D, tol: Optional[Tolerance] = ...
    ) -> Tuple[float, float, float]: ...
    def project_points(
        self, points: List[Point3D], tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float, float]]: ...
    def intersect_cylinder(
        self, other: Cylinder, tol: Optional[Tolerance] = ...
    ) -> Tuple[str, Any]: ...

@final
class Cone:
    def __new__(
        cls, center: Point3D, axis_direction: Vector3D, semi_angle: float, ref_radius: float
    ) -> Cone: ...
    @staticmethod
    def from_frame(frame: Frame3D, semi_angle: float, ref_radius: float) -> Cone: ...
    @staticmethod
    def from_two_points_and_radii(
        p1: Point3D, p2: Point3D, r1: float, r2: float
    ) -> Cone: ...
    def apex(self) -> Point3D: ...
    def semi_angle(self) -> float: ...
    def ref_radius(self) -> float: ...
    def eval_point(self, u: float, v: float) -> Point3D: ...
    def eval_points(self, uvs: List[Tuple[float, float]]) -> List[Point3D]: ...
    def eval_derivative(self, u: float, v: float, du: int, dv: int) -> Vector3D: ...
    def parameters_of(self, point: Point3D) -> Tuple[float, float]: ...
    def contains(self, point: Point3D, tol: Optional[Tolerance] = ...) -> bool: ...
    def project_point(
        self, point: Point3D, tol: Optional[Tolerance] = ...
    ) -> Tuple[float, float, float]: ...
    def project_points(
        self, points: List[Point3D], tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float, float]]: ...
    def intersect_cylinder(
        self, cylinder: Cylinder, tol: Optional[Tolerance] = ...
    ) -> Tuple[str, Any]: ...
    def intersect_cone(self, other: Cone, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...

@final
class Sphere:
    def __new__(cls, center: Point3D, radius: float) -> Sphere: ...
    @staticmethod
    def from_frame(frame: Frame3D, radius: float) -> Sphere: ...
    def center(self) -> Point3D: ...
    def radius(self) -> float: ...
    def area(self) -> float: ...
    def volume(self) -> float: ...
    def eval_point(self, u: float, v: float) -> Point3D: ...
    def eval_points(self, uvs: List[Tuple[float, float]]) -> List[Point3D]: ...
    def eval_derivative(self, u: float, v: float, du: int, dv: int) -> Vector3D: ...
    def parameters_of(self, point: Point3D) -> Tuple[float, float]: ...
    def contains(self, point: Point3D, tol: Optional[Tolerance] = ...) -> bool: ...
    def project_point(
        self, point: Point3D, tol: Optional[Tolerance] = ...
    ) -> Tuple[float, float, float]: ...
    def project_points(
        self, points: List[Point3D], tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float, float]]: ...
    def intersect_sphere(self, other: Sphere, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_cylinder(
        self, cylinder: Cylinder, tol: Optional[Tolerance] = ...
    ) -> Tuple[str, Any]: ...
    def intersect_cone(self, cone: Cone, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...

@final
class Torus:
    def __new__(
        cls, center: Point3D, normal: Vector3D, major_radius: float, minor_radius: float
    ) -> Torus: ...
    @staticmethod
    def from_frame(frame: Frame3D, major_radius: float, minor_radius: float) -> Torus: ...
    def major_radius(self) -> float: ...
    def minor_radius(self) -> float: ...
    def eval_point(self, u: float, v: float) -> Point3D: ...
    def eval_points(self, uvs: List[Tuple[float, float]]) -> List[Point3D]: ...
    def eval_derivative(self, u: float, v: float, du: int, dv: int) -> Vector3D: ...
    def parameters_of(self, point: Point3D) -> Tuple[float, float]: ...
    def contains(self, point: Point3D, tol: Optional[Tolerance] = ...) -> bool: ...
    def project_point(
        self, point: Point3D, tol: Optional[Tolerance] = ...
    ) -> Tuple[float, float, float]: ...
    def project_points(
        self, points: List[Point3D], tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float, float]]: ...
    def intersect_plane(self, plane: Plane, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_sphere(self, sphere: Sphere, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_cylinder(
        self, cylinder: Cylinder, tol: Optional[Tolerance] = ...
    ) -> Tuple[str, Any]: ...
    def intersect_cone(self, cone: Cone, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...
    def intersect_torus(self, other: Torus, tol: Optional[Tolerance] = ...) -> Tuple[str, Any]: ...

@final
class BSplineSurface:
    def __new__(
        cls,
        u_degree: int,
        v_degree: int,
        poles: List[List[Point3D]],
        u_knots: List[float],
        u_multiplicities: List[int],
        v_knots: List[float],
        v_multiplicities: List[int],
        u_periodic: bool,
        v_periodic: bool,
    ) -> BSplineSurface: ...
    @staticmethod
    def new_rational(
        u_degree: int,
        v_degree: int,
        poles: List[List[Point3D]],
        weights: List[List[float]],
        u_knots: List[float],
        u_multiplicities: List[int],
        v_knots: List[float],
        v_multiplicities: List[int],
        u_periodic: bool,
        v_periodic: bool,
    ) -> BSplineSurface: ...
    def u_degree(self) -> int: ...
    def v_degree(self) -> int: ...
    def is_u_periodic(self) -> bool: ...
    def is_v_periodic(self) -> bool: ...
    def is_rational(self) -> bool: ...
    def contains(self, point: Point3D, tol: Optional[Tolerance] = ...) -> bool: ...
    def extrema(
        self, point: Point3D, tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float, float]]: ...
    def project_point(
        self, point: Point3D, tol: Optional[Tolerance] = ...
    ) -> Tuple[float, float, float]: ...
    def project_points(
        self, points: List[Point3D], tol: Optional[Tolerance] = ...
    ) -> List[Tuple[float, float, float]]: ...
    def eval_point(self, u: float, v: float) -> Point3D: ...
    def eval_points(self, uvs: List[Tuple[float, float]]) -> List[Point3D]: ...
    def eval_derivative(self, u: float, v: float, du: int, dv: int) -> Vector3D: ...

__all__ = [
    "BSplineSurface",
    "Cone",
    "Cylinder",
    "Plane",
    "Sphere",
    "Torus",
]
